name: Build Android App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        java-version: [17, 11]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '${{ matrix.java-version }}'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NativeScript CLI
      run: npm install -g nativescript@latest

    - name: Configure NativeScript
      run: |
        mkdir -p $HOME/.local/share/.nativescript-cli/
        echo '{"trackExceptions":false,"trackFeatureUsage":false}' > $HOME/.local/share/.nativescript-cli/user-settings.json
        yes | sdkmanager --licenses > /dev/null 2>&1 || true
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        ns doctor android

    - name: Build Android App
      run: ns build android --release --log trace

    - name: Upload Android Build
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk-java-${{ matrix.java-version }}
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
