name: Build Android App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NativeScript CLI
      run: npm install -g nativescript@latest

    - name: Configure NativeScript
      run: |
        # Create NativeScript config directory and files
        mkdir -p $HOME/.local/share/.nativescript-cli/
        echo '{"trackExceptions":false,"trackFeatureUsage":false}' > $HOME/.local/share/.nativescript-cli/user-settings.json

        # Fix the JSON cache file issue
        echo '{}' > $HOME/.local/share/.nativescript-cli/should-migrate-cache-8.9.3.json

        # Accept Android licenses
        yes | sdkmanager --licenses > /dev/null 2>&1 || true

        # Install required Android components
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # Add Android tools to PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        # Verify environment
        ns doctor android

    - name: Prepare NativeScript Project
      run: |
        # Ensure we're in the right directory
        pwd
        ls -la

        # Clean any previous builds
        ns clean

        # Prepare the project
        ns prepare android

    - name: Build Android App
      run: ns build android --release --log trace

    - name: Upload Android Build
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
