name: Build Android App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    # This is a special step - NativeScript sometimes works better with their own setup process
    - name: Setup NativeScript environment
      run: |
        # Install NativeScript CLI
        npm install -g nativescript@latest

        # Install Android SDK through NativeScript's tooling
        mkdir -p $HOME/.local/share/.nativescript-cli/
        echo '{"trackExceptions":false,"trackFeatureUsage":false}' > $HOME/.local/share/.nativescript-cli/user-settings.json

        # Setup Android SDK
        ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT

        # Download commandline tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT

        # Setup proper directory structure expected by NativeScript
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/ 2>/dev/null || true

        # Set environment variables
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

        # Accept licenses
        yes | sdkmanager --licenses > /dev/null

        # Install required Android SDK components
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # Let NativeScript doctor verify setup
        echo "Verifying environment with NativeScript doctor:"
        ns doctor android

    - name: Build Android App
      run: ns build android --release --log trace

    - name: Upload Android Build
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
