name: Build iOS App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install

    # - name: Install Apple Certificate and Provisioning Profile
    #   env:
    #     P12_BASE64: ${{ secrets.IOS_CERTIFICATE_P12_BASE64 }}
    #     P12_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
    #     PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
    #     KEYCHAIN_PASSWORD: ${{ secrets.GITHUB_RUN_ID }}
    #   run: |
    #     # create a temporary keychain
    #     security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
    #     security default-keychain -s build.keychain
    #     security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        
    #     # import the certificate
    #     printf "%s" "$P12_BASE64" | base64 --decode > certificate.p12
    #     security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A
    #     rm -f certificate.p12

    #     # install the provisioning profile
    #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
    #     printf "%s" "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/build.mobileprovision

    - name: Build iOS
      run: npx nativescript build ios --release
    - name: Upload iOS Build
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: platforms/ios/build/Release-iphonesimulator/KeyPassBLE.app